language: rust
rust:
  - stable
allow_failures:
  - nightly
os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

notifications:
  email:
    on_success: never
before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; else brew update; fi
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y libusb-1.0-0-dev; else brew install libusb; fi

before_script:
- export PATH="$PATH":~/.cargo/bin

script:
- export RUST_BACKTRACE=1
- cargo test --all --verbose
- cargo build --all --verbose --release

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    LOCAL="~/.local" && export PATH=$LOCAL/bin:$PATH &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
    cmake -DCMAKE_INSTALL_PREFIX:PATH=$LOCAL .. && make && make install && cd ../.. &&
    ls target/debug &&
    RUSTFLAGS="-C link-dead-code" cargo test --no-run &&
    for file in target/debug/*; do
      if [[ -x $file ]] && [[ -f $file ]]; then
        mkdir -p "target/cov/$(basename $file)";
        kcov --exclude-pattern=/.cargo,/usr/lib,/usr/include --verify "target/cov/$(basename $file)" "$file";
      fi;
    done &&
    kcov --coveralls-id=$TRAVIS_JOB_ID --merge target/cov target/cov/*

# deploy:
#   provider: releases
#   skip_cleanup: true
#   file: target/release/jade
#   on:
#     repo: etclabs/jade
#     branch: master
#     tags: true